baseURL = 'https://anakenralf.github.io/blog-3DAR/'
languageCode = 'en-us'
title = '3DAR blog'
titlelogo = '3DAR'

[params]  
  dateFormat = "Jan 2, 2006"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"